name = "mightygumball"
type = "javascript"
account_id = "9cb8fb4f8b18159a7929b6ea2b312b6d"
workers_dev = true
route = ""
zone_id = ""
kv_namespaces = [
  { binding = "GUMBALL", id = "78fe2904d3294069bc791916c83474fb", preview_id = "78fe2904d3294069bc791916c83474fb" }
]